<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero('Quick wins.<br>Guaranteed outcomes.','hero-quickwin-corridor-v2.png',array('class'=>'page-hero--quickwin')); ?>

  <section class="section"><div class="shell intro-grid motion"><div><h2>A focused path from use case to measurable result.</h2></div><div class="body-copy"><p class="lede">AI Quick Win solutions are pre-defined, outcome-driven Generative AI packages for digitally ready SMEs.</p><p>Under the MSFT-IMDA GenAIxDigital Leaders Programme, these packages help businesses adopt secure, enterprise-grade AI solutions that are quick to scope, fast to deploy and aligned with operational needs.</p></div></div></section>

  <section class="section section-mist"><div class="shell"><div class="intro-grid motion"><div><h2>AI adoption is moving from exploration into everyday work.</h2></div><div class="body-copy"><p class="lede">The Stanford HAI 2026 AI Index reports that 88% of surveyed organisations used AI in at least one business function in 2025.</p><p>HOSHŌ DIGITAL helps convert that momentum into a governed, practical use case from opportunity discovery through deployment.</p><p><a href="https://hai.stanford.edu/ai-index/2026-ai-index-report/economy" target="_blank" rel="noopener">Source: Stanford HAI, 2026 AI Index Report</a></p></div></div><div class="stat-grid quickwin-stat-grid"><article class="stat"><strong data-count-to="88" data-count-suffix="%">88%</strong><p>of surveyed organisations used AI in at least one business function in 2025.</p></article><article class="stat"><strong data-count-to="70" data-count-suffix="%">70%</strong><p>used generative AI in at least one business function.</p></article><article class="stat"><strong data-count-to="61" data-count-suffix="%">61%</strong><p>reported generative AI adoption in Singapore.</p></article></div></div></section>

  <section class="media-split"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('quickwin-singapore-city.jpg')); ?>')"></div><div class="media-split__content motion"><h2>Built to move from a qualified need to a governed outcome.</h2><div class="feature"><h3>Focused scope</h3><p>Begin with a clearly defined business need and a practical delivery package.</p></div><div class="feature"><h3>Enterprise foundation</h3><p>Configure Microsoft technologies around the way your organisation works.</p></div><div class="feature"><h3>Delivery support</h3><p>Connect opportunity discovery, deployment and internal adoption.</p></div></div></section>

  <section class="section"><div class="shell"><div class="intro-grid motion"><div><h2>Fast. Co-funded. Business-ready. Secure.</h2></div><p>Pre-scoped packages reduce adoption barriers while keeping delivery connected to business needs and responsible AI controls.</p></div><div class="editorial-grid quickwin-outcomes"><article class="feature"><h3>Fast</h3><p>Go live in weeks using ready-to-deploy packages.</p></article><article class="feature"><h3>Co-funded</h3><p>Use programme support to reduce upfront investment.</p></article><article class="feature"><h3>Business-ready</h3><p>Design around real SME workflows, not isolated experiments.</p></article><article class="feature"><h3>Secure</h3><p>Build on Microsoft enterprise technologies and responsible AI practices.</p></article></div></div></section>

  <section class="section section-navy"><div class="shell"><h2>From opportunity to outcome.</h2><div class="process process--arrow process--four"><article><h3>Identify the use case</h3><p>Assess needs such as productivity, customer support, HR or document automation.</p></article><article><h3>Deploy the AI solution</h3><p>Implement Microsoft AI technologies using approved architectures.</p></article><article><h3>Deliver measurable impact</h3><p>Target gains in efficiency, accuracy and decision-making.</p></article><article><h3>Embed adoption</h3><p>Connect technology to people, workflow and operating discipline.</p></article></div></div></section>

  <section class="section"><div class="shell"><div class="intro-grid motion"><div><h2>Enterprise tools, configured around your work.</h2></div><p>The programme combines approved delivery packages with Microsoft’s enterprise AI ecosystem.</p></div><div class="technology-logo-cloud" aria-label="Microsoft technologies"><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('quickwin-copilot-studio.png')); ?>" alt="Microsoft Copilot Studio"></div><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('quickwin-azure-openai.png')); ?>" alt="Azure OpenAI"></div><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('quickwin-copilot.png')); ?>" alt="Microsoft Copilot"></div><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('quickwin-copilot-agents.png')); ?>" alt="Copilot Agents"></div></div></div></section>

  <section class="section section-mist" id="eligibility"><div class="shell qualification-panel motion"><div><h2>Check your eligibility.</h2></div><div><p>If you are a Singapore-registered company with less than S$100 million in annual turnover or fewer than 200 employees, you may qualify. Fill in the form below to register your interest.</p><a class="button" href="https://smesgodigital.gov.sg/web/solution/dl_22/genaixdl-hosho" target="_blank" rel="noopener">Fill in Form<span class="button-arrow" aria-hidden="true"></span></a></div></div></section>
  <?php hosho_render_cta('','Quick wins. Guaranteed outcomes.','','Check eligibility','#eligibility','quickwin-singapore-city.jpg'); ?>
</main><?php get_footer(); ?>
