<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero('We borrow the Earth<br>from our children.','hero-sustainability-earth.jpg',array('class'=>'page-hero--sustainability')); ?>
  <section class="section"><div class="shell intro-grid motion"><div><h2>Long-term resilience is part of our fabric.</h2></div><div class="body-copy"><p class="lede">Our commitments are built around people, communities, responsible business practices and a healthy planet.</p><p>We foster an inclusive culture, support well-being, reduce environmental impact and uphold responsible governance while delivering value to our clients.</p></div></div></section>

  <section class="section section-mist" id="commitments"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Environment</p><h2>Operating with environmental responsibility.</h2></div><p>Explore the commitments below. Hover, focus or tap a card to reveal more.</p></div>
    <div class="esg-commitments" data-esg-cards>
      <article class="esg-card is-active" tabindex="0" aria-expanded="true"><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('esg-singapore-gardens.jpg')); ?>" alt="Gardens by the Bay and Singapore's urban greenery"><div class="esg-card__overlay"><h3>Resource Management</h3><p>Recycling and the sustainable use of resources guide our environmental approach.</p></div></article>
      <article class="esg-card" tabindex="0" aria-expanded="false"><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('sustainability-green-facade.jpg')); ?>" alt="Green building facade in Singapore"><div class="esg-card__overlay"><h3>Emissions &amp; Energy Efficiency</h3><p>We pursue energy-conscious ways of working.</p></div></article>
      <article class="esg-card" tabindex="0" aria-expanded="false"><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('sustainability-cloud-forest.jpg')); ?>" alt="Singapore urban greenery"><div class="esg-card__overlay"><h3>Waste &amp; Pollution Control</h3><p>We consider environmental impact across business activities.</p></div></article>
    </div>
  </div></section>

  <section class="media-split"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('sustainability-singapore.jpg')); ?>')"></div><div class="media-split__content motion"><p class="eyebrow">Social</p><h2>People and communities.</h2><p>We promote a working environment where diverse people can contribute, grow and work with confidence.</p><div class="feature"><h3>Human Capital</h3><p>We foster development, diversity, equity and inclusion.</p></div><div class="feature"><h3>Human Rights</h3><p>We respect the rights of employees, customers, partners and people across our value chain.</p></div><div class="feature"><h3>Social Contributions</h3><p>We build trusted relationships and support responsible procurement.</p></div></div></section>

  <?php hosho_render_quote('A company should not pursue growth for its own sake, but should create value for the world and for people, and contribute to global prosperity.','Konosuke Matsushita','value-konosuke-matsushita.png','quote-band--standard quote-band--balanced'); ?>

  <section class="section"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Governance</p><h2>Trust is sustained through clear standards.</h2></div><p>We work to strengthen corporate governance and comply with applicable laws and regulations under the HOSHŌ DIGITAL Code of Ethics and Business Conduct.</p></div><div class="editorial-grid"><article class="feature"><h3>Internal Controls</h3><p>Fair, transparent corporate behaviour and controls that reflect legal, social and management requirements.</p></article><article class="feature"><h3>Compliance</h3><p>High ethical standards and sincere dealings with stakeholders across the regions where we operate.</p></article><article class="feature"><h3>Information Security</h3><p>Continuous attention to current security measures and responsible handling of information.</p></article></div></div></section>

  <section class="section-sm section-mist"><div class="shell"><div class="logo-row logo-row--credentials"><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('credential-uob-finlab.png')); ?>" alt="UOB FinLab"></div><div><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('credential-enterprise-singapore.png')); ?>" alt="Enterprise Singapore"></div><div class="logo-row__panel--dark"><img loading="lazy" decoding="async" src="<?php echo esc_url(hosho_asset_url('credential-cfi.png')); ?>" alt="Corporate Finance Institute"></div></div></div></section>
</main><?php get_footer(); ?>
