<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero( 'YOUR SUCCESS.<br>OUR GUARANTEE.', 'hero-company-structure.png', array( 'class' => 'page-hero--company' ) ); ?>
  <section class="section"><div class="shell intro-grid motion"><div><p class="eyebrow">Who we are</p><h2>Technology turns potential into reality, and ideas into value.</h2></div><div class="body-copy"><p class="lede">We harness leading-edge technologies to deliver business value and shape how organisations interact with technology.</p><p>The future is not only about technology, but how it can transform an idea into a dependable outcome.</p></div></div></section>
  <section class="media-split media-split--red"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('company-urban-waterfront.jpg')); ?>')"></div><div class="media-split__content motion"><p class="eyebrow">Our name, our standard</p><h2>HOSHŌ <span lang="ja">(保証)</span><br>Our guarantee.</h2><p>We embody our name. We guarantee to deliver what we promise and strive to exceed expectations. We are committed to being a trusted partner, executing everything we do with precision, innovation and unwavering integrity.</p></div></section>
  <section class="section section-mist"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Our north star</p><h2>Built for a hyper-connected, intelligent world.</h2></div><p>Our vision and mission connect responsible ambition with the enterprise digital core.</p></div><div class="editorial-grid"><article class="feature" style="grid-column:span 6"><span class="feature__index">Vision</span><h3>To empower businesses to innovate and grow in a hyper-connected intelligent world.</h3></article><article class="feature" style="grid-column:span 6"><span class="feature__index">Mission</span><h3>To embed intelligence at the heart of the enterprise digital core.</h3></article></div></div></section>
  <section class="section company-values"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Guided by values</p><h2>How we decide and deliver.</h2></div><div class="company-values__intro"><p>Four principles guide the way we work with clients, partners and one another.</p></div></div><div class="company-values__window"><div class="company-values__track company-values__track--grid">
    <article class="company-value"><div class="company-value__visual company-value__visual--portrait" style="background-image:url('<?php echo esc_url(hosho_asset_url('value-soichiro-honda.jpg')); ?>')" role="img" aria-label="Portrait of Soichiro Honda"></div><div class="company-value__copy"><h3>Innovation</h3><p>We embrace creativity, explore the unknown, and pioneer new solutions. We challenge conventions, experiment fearlessly, and stay at the forefront of technology.</p><blockquote>“Action without philosophy is a lethal weapon; philosophy without action is worthless.”</blockquote><cite>Soichiro Honda</cite></div></article>
    <article class="company-value"><div class="company-value__visual company-value__visual--portrait" style="background-image:url('<?php echo esc_url(hosho_asset_url('value-eiichi-shibusawa.jpg')); ?>')" role="img" aria-label="Portrait of Eiichi Shibusawa"></div><div class="company-value__copy"><h3>Trust</h3><p>We believe in transparency, reliability, and accountability. We honour commitments, maintain confidentiality, and build trust with our clients, partners and colleagues.</p><blockquote>“Morality and economy must unite.”</blockquote><cite>Eiichi Shibusawa</cite></div></article>
    <article class="company-value"><div class="company-value__visual company-value__visual--portrait" style="background-image:url('<?php echo esc_url(hosho_asset_url('value-akio-morita.webp')); ?>')" role="img" aria-label="Portrait of Akio Morita"></div><div class="company-value__copy"><h3>Resilience</h3><p>We adapt, overcome and thrive in the face of challenges. We learn from setbacks, bounce back stronger and remain steadfast in our pursuit of excellence.</p><blockquote>“Do not be afraid to make a mistake. But make sure you do not make the same mistake twice.”</blockquote><cite>Akio Morita</cite></div></article>
    <article class="company-value"><div class="company-value__visual company-value__visual--portrait" style="background-image:url('<?php echo esc_url(hosho_asset_url('value-konosuke-matsushita.png')); ?>')" role="img" aria-label="Portrait of Konosuke Matsushita"></div><div class="company-value__copy"><h3>Inclusion</h3><p>We celebrate diversity, create safe spaces, and amplify every voice. We actively listen, remove barriers, and foster an environment where everyone feels valued and empowered.</p><blockquote>“Every single person has their heaven-sent qualities found in no other.”</blockquote><cite>Konosuke Matsushita</cite></div></article>
  </div></div></div></section>
  <?php hosho_render_quote('Do what has never been done before.','Masaru Ibuka','quote-masaru-ibuka.webp','quote-band--standard quote-band--balanced'); ?>
  <section class="section-sm"><div class="shell stat-grid"><article class="stat"><strong>3</strong><p>Locations</p></article><article class="stat"><strong>60+</strong><p>Colleagues</p></article><article class="stat"><strong>6</strong><p>Nationalities</p></article></div></section>
  <?php hosho_render_cta('Your digital guarantee','TURN POTENTIAL INTO PROGRESS.','','Get in touch',hosho_page_url('contact'),'quickwin-digital-landscape.jpg'); ?>
</main><?php get_footer(); ?>
