<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero( 'We borrow the Earth<br>from our children.', 'hero-sustainability-earth.jpg', array( 'class' => 'page-hero--sustainability' ) ); ?>
  <section class="section"><div class="shell intro-grid motion"><div><p class="eyebrow">Sustainability</p><h2>Long-term resilience is part of our fabric.</h2></div><div class="body-copy"><p class="lede">Our commitments are built around people, communities, responsible business practices and a healthy planet.</p><p>We work to foster an inclusive culture, support well-being, reduce environmental impact and uphold responsible governance while delivering value to our clients.</p></div></div></section>
  <section class="section section-mist" id="commitments"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">01 · Environment</p><h2>Operating with environmental responsibility.</h2></div><p>We support resource efficiency, energy awareness and responsible practices across the value chain.</p></div><div class="editorial-grid sustainability-cards">
    <article class="photo-card" style="grid-column:span 5"><img src="<?php echo esc_url(hosho_asset_url('sustainability-green-aerial.jpg')); ?>" alt="Green urban development seen from above"><div class="photo-card__copy"><span class="feature__index">01.1</span><h3>Resource Management</h3><p>Recycling and the sustainable use of resources guide our environmental approach.</p></div></article>
    <article class="photo-card" style="grid-column:span 4"><img src="<?php echo esc_url(hosho_asset_url('sustainability-green-facade.jpg')); ?>" alt="Green building facade"><div class="photo-card__copy"><span class="feature__index">01.2</span><h3>Emissions &amp; Energy Efficiency</h3><p>We pursue energy-conscious ways of working.</p></div></article>
    <article class="photo-card" style="grid-column:span 3"><img src="<?php echo esc_url(hosho_asset_url('sustainability-cloud-forest.jpg')); ?>" alt="Singapore urban greenery"><div class="photo-card__copy"><span class="feature__index">01.3</span><h3>Waste &amp; Pollution Control</h3><p>We consider environmental impact across business activities.</p></div></article>
  </div></div></section>
  <section class="media-split"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('sustainability-team.jpg')); ?>')"></div><div class="media-split__content motion"><p class="eyebrow">02 · Social</p><h2>People and communities.</h2><p>We promote a working environment where diverse people can contribute, grow and work with confidence.</p><div class="feature"><h3>Human Capital</h3><p>We foster development, diversity, equity and inclusion.</p></div><div class="feature"><h3>Human Rights</h3><p>We respect the rights of employees, customers, partners and people across our value chain.</p></div><div class="feature"><h3>Social Contributions</h3><p>We build trusted relationships and support responsible procurement.</p></div></div></section>
  <?php hosho_render_quote('What you do makes a difference, and you have to decide what kind of difference you want to make.','Jane Goodall','jane-goodall-editorial-v2.png','quote-band--standard quote-band--jane'); ?>
  <section class="section"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">03 · Governance</p><h2>Trust is sustained through clear standards.</h2></div><p>We work to strengthen corporate governance and comply with applicable laws and regulations under the HOSHŌ DIGITAL Code of Ethics and Business Conduct.</p></div><div class="editorial-grid"><article class="feature"><span class="feature__index">03.1</span><h3>Internal Controls</h3><p>Fair, transparent corporate behaviour and controls that reflect legal, social and management requirements.</p></article><article class="feature"><span class="feature__index">03.2</span><h3>Compliance</h3><p>High ethical standards and sincere dealings with stakeholders across the regions where we operate.</p></article><article class="feature"><span class="feature__index">03.3</span><h3>Information Security</h3><p>Continuous attention to current security measures and responsible handling of information.</p></article></div></div></section>
  <section class="section-sm section-mist"><div class="shell"><p class="eyebrow">Sustainability credentials</p><div class="logo-row"><div><img src="<?php echo esc_url(hosho_asset_url('credential-uob-finlab.png')); ?>" alt="UOB FinLab"></div><div><img src="<?php echo esc_url(hosho_asset_url('credential-enterprise-singapore.png')); ?>" alt="Enterprise Singapore"></div><div><img class="logo-row__image--dark" src="<?php echo esc_url(hosho_asset_url('credential-cfi.png')); ?>" alt="Corporate Finance Institute"></div><div><strong>Responsible enterprise practice</strong></div></div></div></section>
  <?php hosho_render_cta('Responsible by design','Turn ambition into responsible action.','Talk with HOSHŌ DIGITAL about sustainable, governed digital transformation.','Start a conversation',hosho_page_url('contact'),'sustainability-governance.jpg'); ?>
</main><?php get_footer(); ?>
