<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero( 'Welcome to<br>HOSHŌ DIGITAL.', 'hero-company-structure.png', array( 'class' => 'page-hero--company' ) ); ?>
  <section class="section"><div class="shell intro-grid motion"><div><p class="eyebrow">Who we are</p><h2>Technology turns potential into reality, and ideas into value.</h2></div><div class="body-copy"><p class="lede">We harness leading-edge technologies to deliver business value and shape how organisations interact with technology.</p><p>The future is not only about technology, but how it can transform an idea into a dependable outcome.</p></div></div></section>
  <section class="media-split media-split--red"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('company-urban-waterfront.jpg')); ?>')"></div><div class="media-split__content motion"><p class="eyebrow">Our name, our standard</p><h2>HOSHŌ <span lang="ja">(保証)</span><br>Our guarantee.</h2><p>We embody our name. We guarantee to deliver what we promise and strive to exceed expectations. We are committed to being a trusted partner, executing everything we do with precision, innovation and unwavering integrity.</p></div></section>
  <section class="section section-mist"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Our north star</p><h2>Built for a hyper-connected, intelligent world.</h2></div><p>Our vision and mission connect responsible ambition with the enterprise digital core.</p></div><div class="editorial-grid"><article class="feature" style="grid-column:span 6"><span class="feature__index">Vision</span><h3>To empower businesses to innovate and grow in a hyper-connected intelligent world.</h3></article><article class="feature" style="grid-column:span 6"><span class="feature__index">Mission</span><h3>To embed intelligence at the heart of the enterprise digital core.</h3></article></div></div></section>
  <section class="section"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Guided by values</p><h2>How we decide and deliver.</h2></div><p>Four principles guide the way we work with clients, partners and one another.</p></div><div class="editorial-grid value-grid">
    <article class="photo-card" style="grid-column:span 6"><img src="<?php echo esc_url(hosho_asset_url('value-trust.jpg')); ?>" alt="Architectural detail symbolising trust"><div class="photo-card__copy"><h3>Trust</h3><p>Transparency, reliability and accountability in every commitment.</p></div></article>
    <article class="photo-card" style="grid-column:span 6"><img src="<?php echo esc_url(hosho_asset_url('value-resilience.jpg')); ?>" alt="Resilient urban landscape"><div class="photo-card__copy"><h3>Resilience</h3><p>We learn, adapt and remain steadfast through change.</p></div></article>
    <article class="photo-card" style="grid-column:span 5"><img src="<?php echo esc_url(hosho_asset_url('value-inclusion.jpg')); ?>" alt="Inclusive civic space"><div class="photo-card__copy"><h3>Inclusion</h3><p>We remove barriers, listen actively and value every voice.</p></div></article>
    <article class="photo-card" style="grid-column:span 7"><img src="<?php echo esc_url(hosho_asset_url('value-innovation.jpg')); ?>" alt="Modern structure expressing innovation"><div class="photo-card__copy"><h3>Innovation</h3><p>We explore the unknown and turn ideas into practical value.</p></div></article>
  </div></div></section>
  <?php hosho_render_quote('AI is no longer a single breakthrough or application. It is essential infrastructure. Every company will use it. Every nation will build it.','Jensen Huang','jensen-huang-editorial-v2.png','quote-band--jensen'); ?>
  <section class="section-sm"><div class="shell stat-grid"><article class="stat"><strong>3</strong><p>Locations connecting our teams and clients.</p></article><article class="stat"><strong>60+</strong><p>Colleagues contributing across disciplines.</p></article><article class="stat"><strong>6</strong><p>Nationalities strengthening our perspective.</p></article></div></section>
  <?php hosho_render_cta('Your digital guarantee','Turn potential into dependable progress.','Talk to HOSHŌ DIGITAL about responsible enterprise innovation.','Get in touch',hosho_page_url('contact'),'company-cta-singapore-night.jpg'); ?>
</main><?php get_footer(); ?>
