<?php get_header(); ?>
<main id="main-content">
  <?php hosho_render_hero( 'Quick wins.<br>Guaranteed Outcomes.', 'hero-quickwin-corridor-v2.png', array( 'class' => 'page-hero--quickwin' ) ); ?>
  <section class="section"><div class="shell intro-grid motion"><div><p class="eyebrow">AI Quick Win</p><h2>A focused path from use case to measurable result.</h2></div><div class="body-copy"><p class="lede">AI Quick Win solutions are pre-defined, outcome-driven Generative AI packages for digitally ready SMEs.</p><p>Under the MSFT-IMDA GenAIxDigital Leaders Programme, these packages help businesses adopt secure, enterprise-grade AI solutions that are quick to scope, fast to deploy and aligned with operational needs.</p></div></div></section>
  <section class="section section-mist"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">The evidence</p><h2>Generative AI is moving into business functions.</h2></div><div class="body-copy"><p class="lede">Stanford HAI's 2026 AI Index reports that organisational use of generative AI rose to 79% in 2025, from 71% in 2024.</p><p>HOSHŌ DIGITAL helps convert that momentum into a governed, practical use case, from opportunity discovery through deployment.</p><p><a href="https://hai.stanford.edu/assets/files/ai_index_report_2026_chapter_4_economy.pdf" target="_blank" rel="noopener">Source: Stanford HAI, 2026 AI Index Report</a></p></div></div><div class="stat-grid"><article class="stat"><strong data-count-to="71" data-count-suffix="%">71%</strong><p>Reported organisational use of generative AI in at least one business function in 2024.</p></article><article class="stat"><strong data-count-to="50" data-count-suffix="%">50%</strong><p>Funding available on eligible Quick Win projects.</p></article><article class="stat"><strong data-count-to="20" data-count-prefix="$" data-count-suffix="K">$20K</strong><p>Maximum eligible project value under the programme.</p></article></div></div></section>
  <section class="media-split"><div class="media-split__image" style="background-image:url('<?php echo esc_url(hosho_asset_url('quickwin-singapore-city.jpg')); ?>')"></div><div class="media-split__content motion"><p class="eyebrow">Programme essentials</p><h2>Funding, eligibility and support.</h2><div class="feature"><h3>Funding</h3><p>Unlock 50% funding on projects up to $20,000 under the Quick Win Programme.</p></div><div class="feature"><h3>Eligibility</h3><p>Open to Singapore-based businesses with at least 30% local shareholding.</p></div><div class="feature"><h3>Support</h3><p>HOSHŌ DIGITAL supports the AI journey from opportunity discovery to solution deployment.</p></div></div></section>
  <section class="section"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Business outcomes</p><h2>Fast. Co-funded. Business-ready. Secure.</h2></div><p>Pre-scoped packages reduce adoption barriers while keeping delivery connected to business needs and responsible AI controls.</p></div><div class="editorial-grid quickwin-outcomes"><article class="feature"><h3>Fast</h3><p>Go live in weeks using ready-to-deploy packages.</p></article><article class="feature"><h3>Co-funded</h3><p>Use programme support to reduce upfront investment.</p></article><article class="feature"><h3>Business-ready</h3><p>Design around real SME workflows, not isolated experiments.</p></article><article class="feature"><h3>Secure</h3><p>Build on Microsoft enterprise technologies and responsible AI practices.</p></article></div></div></section>
  <section class="section section-navy"><div class="shell"><h2>From opportunity to outcome.</h2><div class="process process--arrow"><article><h3>Identify the use case</h3><p>Assess needs such as productivity, customer support, HR or document automation.</p></article><article><h3>Deploy the AI solution</h3><p>Implement Copilot, AI Agents or Azure OpenAI using pre-approved architectures.</p></article><article><h3>Deliver measurable impact</h3><p>Target gains in efficiency, accuracy and decision-making.</p></article><article><h3>Embed adoption</h3><p>Connect technology to people, workflow and operating discipline.</p></article></div></div></section>
  <section class="section"><div class="shell"><div class="intro-grid motion"><div><p class="eyebrow">Microsoft technologies</p><h2>Enterprise tools, configured around your work.</h2></div><p>The programme combines approved delivery packages with Microsoft’s enterprise AI ecosystem.</p></div><div class="technology-logo-cloud" aria-label="Microsoft technologies"><div><img src="<?php echo esc_url(hosho_asset_url('quickwin-copilot-studio.png')); ?>" alt="Microsoft Copilot Studio"></div><div><img src="<?php echo esc_url(hosho_asset_url('quickwin-azure-openai.png')); ?>" alt="Azure OpenAI"></div><div><img src="<?php echo esc_url(hosho_asset_url('quickwin-copilot.png')); ?>" alt="Microsoft Copilot"></div><div><img src="<?php echo esc_url(hosho_asset_url('quickwin-copilot-agents.png')); ?>" alt="Copilot Agents"></div></div></div></section>
  <section class="section section-mist"><div class="shell qualification-panel motion"><div><h2>Find out if you qualify.</h2></div><div><p>Singapore-based businesses with at least 30% local shareholding can submit their details for a prompt eligibility review. HOSHŌ DIGITAL will outline the programme requirements and next steps before an engagement begins.</p><a class="button" href="https://hoshodigital.com/ai-quick-win-form/">Check eligibility<span class="button-arrow" aria-hidden="true"></span></a></div></div></section>
  <?php hosho_render_cta( 'Low risk. High impact.', 'Quick wins. Guaranteed Outcomes.', 'Discuss whether AI Quick Win is the right starting point for your organisation.', 'Register interest', 'https://hoshodigital.com/ai-quick-win-form/', 'quickwin-singapore-city.jpg' ); ?>
</main>
<?php get_footer(); ?>
